\set ON_ERROR_STOP on

REVOKE CONNECT, TEMPORARY ON DATABASE :"DBNAME" FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE ROLE app_user
    LOGIN
    PASSWORD 'app_dev_password'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

CREATE ROLE saq_user
    LOGIN
    PASSWORD 'saq_dev_password'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

GRANT CONNECT ON DATABASE :"DBNAME" TO app_user, saq_user;

CREATE SCHEMA app AUTHORIZATION app_user;
CREATE SCHEMA saq AUTHORIZATION saq_user;

REVOKE ALL ON SCHEMA app FROM PUBLIC, saq_user;
REVOKE ALL ON SCHEMA saq FROM PUBLIC, app_user;
GRANT USAGE, CREATE ON SCHEMA app TO app_user;
GRANT USAGE, CREATE ON SCHEMA saq TO saq_user;

ALTER ROLE app_user IN DATABASE :"DBNAME" SET search_path TO pg_catalog, app;
ALTER ROLE saq_user IN DATABASE :"DBNAME" SET search_path TO saq, pg_catalog;

ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA app
    REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA app
    REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA app
    REVOKE ALL ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE saq_user IN SCHEMA saq
    REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE saq_user IN SCHEMA saq
    REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE saq_user IN SCHEMA saq
    REVOKE ALL ON FUNCTIONS FROM PUBLIC;
